// 20 - React Web App - Part 2/Beginning of Chapter/reactapp/src/categoryList.tsx
import React, { Component } from "react";

interface Props {
    selected: string,
    categories: string[],
    selectCategory: (category: string) => void;
}

export class CategoryList extends Component<Props> {

    render() {
        return <div>
            { ["All", ...this.props.categories].map(c => {
                let btnClass = this.props.selected === c 
                    ? "btn-primary": "btn-secondary";
                return <button key={ c }
                        className={ `btn btn-block ${btnClass}` } 
                        onClick={ () => this.props.selectCategory(c) }>
                    { c }
                </button>
            }) }
        </div>
    }
}

// 22 - Vue.js Web App - Part 2/End of Chapter/vueapp/src/components/CategoryList.vue
<template>
    <div>
        <button v-for="c in categories" 
            v-bind:key="c"
            v-bind:class="getButtonClasses(c)"
            @click="selectCategory(c)">
                {{ c }}
        </button>
    </div>

</template>

<script lang="ts">

import { defineComponent, PropType } from "vue";

export default defineComponent({
    name: "CategoryList",
    props: {
        categories: {
            type: Object as PropType<string[]>
        },
        selected: {
            type: String as PropType<string>
        }
    },
    methods: {
        selectCategory(category: string) {
            this.$emit("selectCategory", category);
        },

        getButtonClasses(category: string): string {
            const btnClass = this.selected === category 
                ? "btn-primary": "btn-secondary";
            return `btn btn-block ${btnClass}`;
        }
    }
});
</script>
