// 17 - Angular Web App - Part 1/angularapp/src/app/header.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { Order } from './data/entities';

@Component({
    selector: "header",
    templateUrl: "./header.component.html"
})
export class Header {

    @Input()
    order: Order;

    @Output()
    submit = new EventEmitter<void>();

    get headerText(): string {
        let count = this.order.productCount;
        return count === 0 ? "(No Selection)"
            : `${ count } product(s), $${ this.order.total.toFixed(2)}`
    }
}

<div class="p-1 bg-secondary text-white text-right">
  {{ headerText }}
  <button class="btn btn-sm btn-primary m-1" (click)="submit.emit()">
      Submit Order
  </button>
</div>

// 22 - Vue.js Web App - Part 2/End of Chapter/vueapp/src/components/Header.vue
<template>
            
    <div class="p-1 bg-secondary text-white text-right">
        {{ displayText }} 
        <router-link to="/order" class="btn btn-sm btn-primary m-1">
            Submit Order
        </router-link>
    </div>

</template>

<script lang="ts">

import { defineComponent, PropType} from "vue";
import { Order } from "../data/entities";
import { useStore } from "vuex";

export default defineComponent({
    name: "Header",
    setup() {
        return { store:  useStore() }
    },
    computed: {
        displayText(): string {
            const count = this.store.state.order.productCount;
            return count === 0 ? "(No Selection)" 
                : `${ count } product(s), ` 
                    + `$${ this.store.state.order.total.toFixed(2)}`;
        }        
    }
})
</script>
