// 20 - React Web App - Part 2/End of Chapter/reactapp/src/productList.tsx
import React, { Component } from "react";
import { Header } from "./header";
import { ProductItem } from "./productItem";
import { CategoryList} from "./categoryList";
import { Product, Order } from "./data/entities";

interface Props {
    products: Product[],
    categories: string[],
    order: Order,
    addToOrder: (product: Product, quantity: number) => void
}

interface State {
    selectedCategory: string;
}

export class ProductList extends Component<Props, State> {

    constructor(props: Props) {
        super(props);
        this.state = {
            selectedCategory: "All"
        }
    }

    render() {
        return <div>
            <Header order={ this.props.order } />
            <div className="container-fluid">
                <div className="row">
                    <div className="col-3 p-2">
                        <CategoryList categories={ this.props.categories } 
                            selected={ this.state.selectedCategory }
                            selectCategory={ this.selectCategory } />
                    </div>
                    <div className="col-9 p-2">
                        {
                            this.products.map(p => 
                                <ProductItem key={ p.id } product={ p } 
                                    callback={ this.props.addToOrder } />)
                        }
                    </div>
                </div>
            </div>
        </div>
    }

    get products(): Product[] {
        return this.props.products.filter(p => this.state.selectedCategory === "All" 
            || p.category === this.state.selectedCategory);
    }

    selectCategory = (cat: string) => {
        this.setState({ selectedCategory: cat});
    }
}

// 18 - Angular Web App - Part 2/Beginning of Chapter/angularapp/src/app/productList.component.ts
import { Component } from "@angular/core";
import { DataSource } from './data/dataSource';
import { Product } from './data/entities';

@Component({
    selector: "product-list",
    templateUrl: "./productList.component.html"
})
export class ProductList {
    selectedCategory = "All";

    constructor(public dataSource: DataSource) {}

    get products(): Product[] {
        return this.dataSource.getProducts("id",
            this.selectedCategory === "All" ? undefined : this.selectedCategory);
    }

    get categories(): string[] {
        return ["All", ...this.dataSource.getCategories()];
    }

    handleCategorySelect(category: string) {
        this.selectedCategory = category;
    }

    handleAdd(data: {product: Product, quantity: number}) {
        this.dataSource.order.addProduct(data.product, data.quantity);
    }

    handleSubmit() {
        console.log("SUBMIT");
    }
}

<header [order]="dataSource.order" (submit)="handleSubmit()"></header>
<div class="container-fluid">
    <div class="row">
        <div class="col-3 p-2">
            <category-list [selected]="selectedCategory" [categories]="categories"
                (selectCategory)="handleCategorySelect($event)"></category-list>
        </div>
        <div class="col-9 p-2">
            <product-item *ngFor="let p of products" [product]="p"
                (addToCart)="handleAdd($event)"></product-item>
        </div>
    </div>
</div>
